import '../models/report.dart';

/// Contract for report data sources (mock or remote).
///
/// Reports are generated by the backend (which can render PDF/Excel
/// variants). The app consumes structured [Report] rows and formats
/// them locally.
abstract class ReportRepository {
  /// Donation reports for a period.
  Future<List<Report>> getDonationReports(ReportPeriod period);

  /// Campaign reports for a period.
  Future<List<Report>> getCampaignReports(ReportPeriod period);

  /// Charity reports for a period.
  Future<List<Report>> getCharityReports(ReportPeriod period);

  /// Fetches a donation receipt (structured, printable).
  Future<DonationReceipt> getDonationReceipt(String donationId);
}
